### ISSUE TITLE
VIN 1FBNE3BE1CDB23596 doesn't return any results

### ISSUE THREAD

**Issue by lucasmocellin** [arpuffer/pyvin#8]
VIN('1FBNE3BE1CDB23596') returns an empty list []

additionally if doing a pyvin.clean_vins('1FBNE3BE1CDB23596') it also returns an empty

My guess is the VIN validator is considering this an invalid VIN, which is not the case. it is valid:
https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValues/1FBNE3BE1CDB23596

@arpuffer not sure if you're still working on this, but here it is. I am not a software engineer myself, but a Product Manager dangerous enough with code, I would love to be able to solve this myself but I couldn't figure that out. Thank you very much in advance!

**Comment by arpuffer** [comment]
Check ErrorText--this VIN is not valid and while VPIC will attempt a decode it also tells you that it's invalid.  On the web UI things look a little more helpful

` Error Text: 1 - Check Digit (9th position) does not calculate properly; 3 - VIN corrected, error in one position (assuming Check Digit is correct); 14 - Unable to provide information for some of the characters in the VIN, based on the manufacturer submission. `

I have not been active on this project in a very long time, but it may be a reasonable change to have pyvin skip VIN validation and send to the VPIC API anyway. For the moment this code is functioning as expected, if a VIN is invalid we will not ask VPIC to decode it.

**Comment by arpuffer** [comment]
@lucasmocellin closing this issue in favor of https://github.com/arpuffer/pyvin/issues/9

PyVIN is currently working as expected, but I think the next version should work with VINs like the one you tried.

**Comment by lucasmocellin** [comment]
that makes sense, haven't noticed that ErrorText field. Thanks for the quick response and the complete explanation @arpuffer .
